/*
 * This file is generated by jOOQ.
 */
package superservice.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import superservice.db.tables.Uploads;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UploadsRecord extends UpdatableRecordImpl<UploadsRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 273288771;

    /**
     * Setter for <code>uploads.id</code>.
     */
    public UploadsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>uploads.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>uploads.user_id</code>.
     */
    public UploadsRecord setUserId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>uploads.user_id</code>.
     */
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>uploads.payload_md5</code>.
     */
    public UploadsRecord setPayloadMd5(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>uploads.payload_md5</code>.
     */
    public String getPayloadMd5() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Uploads.UPLOADS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Uploads.UPLOADS.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Uploads.UPLOADS.PAYLOAD_MD5;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPayloadMd5();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPayloadMd5();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UploadsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UploadsRecord value2(String value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UploadsRecord value3(String value) {
        setPayloadMd5(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UploadsRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UploadsRecord
     */
    public UploadsRecord() {
        super(Uploads.UPLOADS);
    }

    /**
     * Create a detached, initialised UploadsRecord
     */
    public UploadsRecord(Integer id, String userId, String payloadMd5) {
        super(Uploads.UPLOADS);

        set(0, id);
        set(1, userId);
        set(2, payloadMd5);
    }
}
