/*
 * This file is generated by jOOQ.
 */
package superservice.db;


import javax.annotation.Generated;

import superservice.db.tables.Uploads;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>uploads</code>.
     */
    public static final Uploads UPLOADS = superservice.db.tables.Uploads.UPLOADS;
}
