/*
 * This file is generated by jOOQ.
 */
package superservice.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Uploads implements Serializable {

    private static final long serialVersionUID = -1166393913;

    private final Integer id;
    private final String  userId;
    private final String  payloadMd5;

    public Uploads(Uploads value) {
        this.id = value.id;
        this.userId = value.userId;
        this.payloadMd5 = value.payloadMd5;
    }

    public Uploads(
        Integer id,
        String  userId,
        String  payloadMd5
    ) {
        this.id = id;
        this.userId = userId;
        this.payloadMd5 = payloadMd5;
    }

    public Integer getId() {
        return this.id;
    }

    public String getUserId() {
        return this.userId;
    }

    public String getPayloadMd5() {
        return this.payloadMd5;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Uploads (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(payloadMd5);

        sb.append(")");
        return sb.toString();
    }
}
